apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-keycloak
  namespace: flux-system
spec:
  dependsOn:
    - name: apps-keycloak-db
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: demo-flux
  path: ./apps/keycloak
  targetNamespace: keycloak
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age