apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kc-postgresql
spec:
  interval: 1h
  chart:
    spec:
      chart: postgresql
      version: "12.10.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1h
  values:
    auth:
      username: admin
      existingSecret: kc-db-password
      database: kc