apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kuma
spec:
  interval: 1h
  chart:
    spec:
      chart: kuma
      version: "2.3.2"
      sourceRef:
        kind: HelmRepository
        name: kuma
        namespace: flux-system
      interval: 1h