---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-kuma
  namespace: flux-system
spec:
  dependsOn:
    - name: core-base
    - name: core-kuma
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: demo-flux
  path: ./infrastructure/configs/kuma
  prune: true