apiVersion: v1
data:
    password: ENC[AES256_GCM,data:pQhNTqAnFLw=,iv:ZjTHO3qx8+FQirc44dWm/7vc/GIIHXfcSKwEPSYaC2g=,tag:UDPdr2Bps8x2tHB8wFLRXQ==,type:str]
kind: Secret
metadata:
    name: kc-admin-password
    namespace: keycloak
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10dqrfr7ry7ml3y3vq7g7swwwkzpgrk0sq58pcyhjhxpr5qy0gqwsf20yne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvd0NRWjZWTEFiMUlydGw1
            dHcrQmF6b0F0bnVOMVJKck1tbU12R0VvTlNVCkpLRUdybDVxZnV5Lzdmb2NhT011
            SlR6c2I4Qi96Wml3bzkxZ1dFRlZpWWcKLS0tIGo5UEZqOG5sNGJubDUrWEliNWxK
            dG9lMGNSc01CZlVJYzFqU296ejJOUUkKAB8HdQcOohUMzzXlsWkTPu4UmFXJxUPD
            ux6zrKbnt8LbB9TZeCXGBtT8WqydaguP1hyzBZBfQ6BOxRtIyA7DQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T03:14:33Z"
    mac: ENC[AES256_GCM,data:RnlycAx575gQpF0BA03zuJmVw1WwAdSwGdTXHdWLwL+TlNU/HVotFTBBy3Kun50NEfT7kY/VwrE2e9Lprc/uPQ6Bo6y2SrPO0YTXEqtn57Tb6t+4GSzt3AdkM6eLBWu81X/YmnXR6mqnylFzoc5CGkI+SdjNpCBwGGQZ1itYPj8=,iv:/kmLJ4KN4JzXL0/RR9dZLNFEjLh1k8LrsIXdQr/I9vw=,tag:fr7ufSnA5Jhll4ZGxsLGZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1