apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 1h
  chart:
    spec:
      chart: keycloak
      version: "16.1.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 1h
  values:
    auth:
      existingSecret: kc-admin-password
      passwordSecretKey: password
      adminUser: admin
    production: true
    proxy: edge
    postgresql:
      enabled: false
    externalDatabase:
      host: "kc-postgresql"
      port: 5432
      user: admin
      database: kc
      existingSecret: kc-db-password
      existingSecretPasswordKey: postgres-password