apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-prometheus
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  bandwidth_metrics: true
  upstream_health_metrics: true
  latency_metrics: true
  per_consumer: true
  status_code_metrics: true
plugin: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-gateway-kong
  namespace: monitoring
  labels:
    release: prometheus
spec:
  jobLabel: kong-gateway
  namespaceSelector:
    matchNames:
    - kong
  selector:
    matchLabels:
      app.kubernetes.io/instance: kong-gateway
      app.kubernetes.io/name: kong
  endpoints:
  - scheme: http
    targetPort: status