apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-kong
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
  - name: cluster-helm-repos
  # - name: core-kong-ingress
  sourceRef:
    kind: GitRepository
    name: demo-flux
  path: ./infrastructure/base/kong
  prune: true
  targetNamespace: kong
  decryption:
    provider: sops
    secretRef:
      name: sops-age