apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-kong-ingress
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
  - name: core-kuma
  - name: cluster-helm-repos
  sourceRef:
    kind: GitRepository
    name: demo-flux
  path: ./infrastructure/base/kong-ingress
  prune: true
  targetNamespace: kong