apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kong
commonLabels:
  app.kubernetes.io/name: kong
  app.kubernetes.io/instance: kong
resources:
  - namespace.yaml
  - ca-enc.yaml
  - client-enc.yaml
  - kong-gateway.yaml
  - kong-ingress.yaml
patches:
  - target:
      kind: Namespace
      name: kong
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          kuma.io/sidecar-injection: enabled