apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kong
commonLabels:
  app.kubernetes.io/name: kong
  app.kubernetes.io/instance: kong
resources:
  - namespace.yaml
  - ca-enc.yaml
  - client-enc.yaml