---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo-flux
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: demo-flux-auth
  url: ssh://git@github.com/liyangau/flux-demo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-configuration
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/demo/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab-flux
