image:
  repository: kong
  tag: "3.5"

ingressController:
  enabled: false

replicaCount: 1

manager:
  enabled: false

admin:
  enabled: true
  type: ClusterIP
  tls:
    client:
      secretName: admin-api-ca-cert
