apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kong
commonLabels:
  app.kubernetes.io/name: kong-ingress
  app.kubernetes.io/instance: kong-ingress
resources:
  - namespace.yaml
  - release.yaml
# patches:
#   - target:
#       kind: Namespace
#       name: kong
#     patch: |-
#       - op: add
#         path: /metadata/labels
#         value:
#           kuma.io/sidecar-injection: enabled
configMapGenerator:
  - name: kong-ingress-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml