apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: httpbin
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- namespace.yaml
patches:
  - target:
      kind: Namespace
      name: httpbin
    patch: |-
      - op: add
        path: /metadata/labels
        value:
          kuma.io/sidecar-injection: enabled