apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-apps
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cluster-helm-repos
    - name: infra-base
  sourceRef:
    kind: GitRepository
    name: demo-flux
  path: ./clusters/demo/apps
  prune: true