apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-base
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cluster-helm-repos
  sourceRef:
    kind: GitRepository
    name: homelab-flux
  path: ./clusters/homelab/core
  prune: true