apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-base
  namespace: flux-system
spec:
  interval: 5m
  dependsOn:
    - name: cluster-helm-repos
  sourceRef:
    kind: GitRepository
    name: demo-flux
  path: ./clusters/demo/core
  prune: true