---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: core-base
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: demo-flux
  path: ./infrastructure/configs/cert-manager
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age