---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config-kong
  namespace: flux-system
spec:
  dependsOn:
    - name: core-base
    - name: core-kong-gateway
    - name: core-kong-ingress
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: demo-flux
  path: ./infrastructure/configs/kong
  prune: true