apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kong
commonLabels:
  app.kubernetes.io/name: kong-gateway
  app.kubernetes.io/instance: kong-gateway
resources:
  - release.yaml
configMapGenerator:
  - name: kong-gateway-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml