apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
commonLabels:
  app.kubernetes.io/name: prometheus-stack
  app.kubernetes.io/instance: prometheus-stack
resources:
  - namespace.yaml
  - release.yaml
  - ingress.yaml