apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "50.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 1h
  values:
    grafana:
      # adminPassword: prom-operator
      defaultDashboardsTimezone: Australia/Melbourne